### ISSUE TITLE
(M&L: SS +) Bowser's Minions Cheats not Working

### ISSUE THREAD

**Issue by TariqJL** [FlagBrew/Sharkive#117]
Title ID: 00040000001B8F00
Product code: ?
Game version: ?
Luma version: 9.1

I've only tried to use the last 5 codes. They don't work. I haven't updated the game, so it should be the first version. All the codes have stars next to them, not certain what that means. Working codes please XO.

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Also since you didn't understand what the `*'s` next to the code names meant, please retest them with the above combos that spiredmoth had given you for the 5 codes that you tested.

Thank you!

**Comment by TariqJL** [comment]
I tested the same 5 codes again using v9.1-bd15f51a of Luma. Still no luck.
