### ISSUE TITLE
Star Fox 64 3D

### ISSUE THREAD

**Issue by omega59** [FlagBrew/Sharkive#122]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected should give Max of the item cheats**:
* **Nothing changed when cheat is enabled, or even when items used or collected to add more.**:

### Fill this for problems with codes in the database

* **00030400**:
* **CTR-G-ZLDU**:
* **Game version**:
* **Luma 9.1-89cc6ed**:

### Not working codes

* Max Silver ring in training
* Max hits
* Max gold rings
* Unlimited bombs
* Infinite lives

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

----

Also these codes are for Star Fox 64 3D (JPN) not The Legend of Zelda Links Awakening.

**Comment by omega59** [comment]
Not according to shark drive it listed it for links awakening, which is a VC game and for gameboy original.

**Comment by JourneyOver** [comment]
So I did a little bit of research, and there is no true VC release of The Legend of Zelda Links Awakening of the gameboy version, the only version released for VC is the The Legend of Zelda Links Awakening DX re-release which is a gameboy color (and a totally different titleID to the one you gave me and widly different cheats to the ones you listed as well).

So pretty much what I'm saying is that you are not running a true VC game at all, and it's actually an injected VC which I assume is being injected into the "Star Fox 64 3D (JPN)" cia from what I can at least tell due to the fact that both the TitleID and the cheats you listed are for Star Fox 64 3D (JPN) and the research that I have done looking up legend of zelda VC releases for the 3DS.

If you think this is wrong and you can prove it somehow then feel free to re-open this and continue on with the discussion, but for now I'm marking this as invalid due to the research I have done and closing this issue.

**Comment by omega59** [comment]
Ohhhh I wasn't aware it was injected. Okay makes sense why the codes never worked. But this means I need to find a proper version of this game and try codes with that. How crap, BC I made it pretty far in the game. Thank you for the information.
