### ISSUE TITLE
Fire Emblem Fates - Special Edition (EUR) weapon mastering code

### ISSUE THREAD

**Issue by nhat241010** [FlagBrew/Sharkive#127]
### Not working codes

*[(SELECT+Y)Mastering weapon v1.0]
DD000000 00000804
D3000000 00000000
B06DA0D8 00000000
C0000000 000000FA
000000E8 FFFFFFFF
000000EC FFFFFFFF
60000014 00000000
B0000014 00000000
D0000000 00000000
D1000000 00000000
D0000000 00000000

**Comment by JourneyOver** [comment]
1. Please next time fill out the issue template form..**do not remove it, and just do what you please** otherwise issue will be closed without any removal of broken codes..

2. Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
