### ISSUE TITLE
Devil Survivor Overclocked

### ISSUE THREAD

**Issue by redhshadow** [FlagBrew/Sharkive#130]
## Issue template

* [] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:00038800
* **Product code**:
* **Game version**:
* **Luma version**:

### Not working codes

* max macca
* ser  main st
* set main ma
* set main vi
* set main ag
* set main all stats
* main character - max level and stats
* main character - command and passives
* team 2 leader - max level and stats
* team 2 leader - command and passives
* team 1, slot 1 demon - max level and stats
* team 1, slot 1 demon - command and passives

**Comment by JourneyOver** [comment]
Okay so I will need a bit more information on this before I proceed to do anything for this issue.

1. Fill out the `Product Code`, `Game version` and `Luma Version`.
2. if you are running the 9.1 release of luma please test with luma nightly which you can grab from https://github.com/hax0kartik/luma-hourlies/releases
3. Are you running the normal english release, or are you running a Undubbed release?

Failing to do so within 7 days will result in the issue being closed without removal of broken codes.

**Comment by redhshadow** [comment]
Right, well i am not entirely sure how to get the product code, but I am using the 9.1 luma version, and its the undubbed version. I have not tried the nightly ver though.

**Comment by JourneyOver** [comment]
You can find the product code in sharkives menu, it should start with `CTR`, and yes please test with the nightly version of luma, which you can grab at the link above and can you please tell me what is the version (like 1.0/1.1/1.2 and so forth) of the game as you still have not provided that information either.

If anything this might just be a case of the undubbed version being completely different to the original release of the game in the way codes work, but it could also be a version difference as well (codes being made for 1.0 while you are maybe running 1.1)

**Comment by redhshadow** [comment]
I have tested the latest nightly ver. and no luck, as for the product code it is CTR-P-AMTE. And as far as the game version goes, i have never updated it, so it would be likely to assume that its at its either original or latest ver.

**Comment by JourneyOver** [comment]
Okay thanks, I will take a closer look into things when I get a chance (which right now my time is pretty limited so it might be a bit), it could just end up being broken codes which if that's the case then they will be removed otherwise the cheat names will be updated to reflect which version they are for.

**Comment by JourneyOver** [comment]
So I looked a bit more into this, and it looks to be a case of normal release vs the undubbed version, as from just my little testing phase it seems that all the codes work on the normal release.. So I'm going to go ahead and close this issue, due to the fact that the codes work. So I'd suggest maybe switching over to the normal release, instead of using the undubbed release if you want cheats.
