### ISSUE TITLE
The codes doesnt work

### ISSUE THREAD

**Issue by dextra03** [FlagBrew/Sharkive#137]
### Not working codes
All the codes of animal crossing new leaf doesnt work

**Comment by JourneyOver** [comment]
Two things..

1. You didn't fill out the issue template at all, which is an automatic closure until you fill out the issue template (and then you'd be free to re-open the issue once you filled it out).

2. Yes the AC:NL codes are borked, we are waiting on @Slattz to get around to sending a PR since he said he was going to eventually, that will update the ones in the DB ontop of including all the other regions as well. Right now it's advised to just use NTR plugins for AC:NL until he can do so.

anyways closing this due to 1.
