### ISSUE TITLE
Tomodachi Life EUR codes don't work

### ISSUE THREAD

**Issue by chxngeling** [FlagBrew/Sharkive#141]
* [] All of them don't work on my EUR game cartridge.

* **Title ID**: 0008C400
* **Product code**: CTR-P-EC6P
* **Game version**: 2.0
* **Luma version**: 9.1

### Not working codes

* All 4 available codes on the data base from version 1.0.0 on date of writing. (24th of march 2019)

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

Also to note: since you are running version 2.0, this will only count for the Version 2.0 codes, unless you downgrade your game to 1.0 and test the Version 1.0 codes as well.

**Comment by chxngeling** [comment]
Ok, thank you! I will test this once I can.

**Comment by chxngeling** [comment]
I redid it with the most recent luma nightly, and the ver 2 codes still have no effect.

**Comment by JourneyOver** [comment]
Closes out by https://github.com/FlagBrew/Sharkive/commit/dd1d9277701493fa9cf06d83985f9fb4695520b7
