### ISSUE TITLE
Sharkive closes after loading screen.

### ISSUE THREAD

**Issue by Dino1989** [FlagBrew/Sharkive#149]
What the title says. I'm not sure why it started doing it now as I don't recall making any changes other than installing a new CIA (it's a 3DS game).

**Comment by dextra03** [comment]
Yes me too.

**Comment by JourneyOver** [comment]
This is happening due to sharkive not being able to load the Database anymore, due to recent changes in this repository. Current form of sharkive is pretty much obsolete as of now and will no longer work, sharkive is slowly be worked into checkpoint which should be releasing sometime in the near future.

For now you'll just need to manually download the cheat.txt files you want and place them in the correct location. Which is `sd:/luma/titles/title_ID/cheats.txt` substituting `title_ID` with the title ID of the game.

I'm going to leave this issue open so anyone else who comes along and wonders why this is happening can look at this answer to find out the reasoning.

**Comment by dextra03** [comment]
Oh no :(

**Comment by piepie62** [comment]
This is the process of Sharkive getting better, so I don't see the reason you would be sad

**Comment by felipechalreo** [comment]
Can't wait for the update.

**Comment by golephish** [comment]
thank you for the updates! I was going mad as I wasn't able to update a recent title! So does this mean it can be done in checkpoint now?

**Comment by quil0208** [comment]
From the FlagBrew Discord:

> the switch version is mostly done from what I can tell (I don't know exactly what is left to do on it), and the 3DS version is still in very early stages (not even started yet from my guess).

So yeah, you will be able to use Checkpoint... eventually.

**Comment by JourneyOver** [comment]
Thank you for posting that @quil0208 

It can't be done with checkpoint right now @golephish but it's coming, I can't give an estimate date on when the arrival will be as there are still things that need to be done on the switch version of checkpoint (though switch is mostly done for the most part, and 3ds hasn't really started yet), but once it's done you'll be able to use checkpoint to download cheats for both 3DS (which will still use rosalina's menu for cheat activation) and Switch (which will use Atmosphere for cheat activation).

**Comment by golephish** [comment]
thank you as always for teh quick reply! Silly question - as I LOVE the simplicty of sharkive ... if I clone the cheats DB --- do I have to create title IDs for each cheat, or can I use the AR replay plugin and just dump the whole thing?

**Comment by jflambert** [comment]
Thanks for the info @JourneyOver . I'm a new user so I thought for sure I was doing something wrong. Tried reinstalling it multiple times.

It'd be nice to have a failure message from within Sharkive though, as opposed to it just shutting down. Something a little more verbose (couldn't connect / download / etc)

**Comment by golephish** [comment]
well I tried again this morning and it sprang to life. it was able to access the database for me this time :)

**Comment by JourneyOver** [comment]
> well I tried again this morning and it sprang to life. it was able to access the database for me this time :)

This is due to the fact that we renamed the 3DS folder back to just db for now, until we fully deprecate sharkive @golephish 

> Thanks for the info @JourneyOver . I'm a new user so I thought for sure I was doing something wrong. Tried reinstalling it multiple times.
> 
> It'd be nice to have a failure message from within Sharkive though, as opposed to it just shutting down. Something a little more verbose (couldn't connect / download / etc)
> 
> But if Sharkive is to be made completely obsolete then it should be clearly stated on the github, and also the hacking guide should remove all links to Sharkive.

@jflambert Thing is we do not plan on doing anymore releases of sharkive anymore so there will never be a failure message or anything. as for the "But if Sharkive is to be made completely obsolete then it should be clearly stated on the github" the thing is, is that this repository is now being turned into just a database of cheats for when checkpoint has the cheat stuff fully implemented and released for both switch and 3DS, and well we can't really comment on hacking guides having links for sharkive. We have reached out to some people to tell them to drop sharkive support on various things but there are some that we can't really reach.
