### ISSUE TITLE
yo kai watch cheat not working

### ISSUE THREAD

**Issue by Andredwiputra** [FlagBrew/Sharkive#167]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3ds
* **Title ID**:
* **Product code**: 
* **Game version**: yokai watch update version 1.2
* **Luma version**: 10.0
* **Atmosphere-NX version**:

### Not working codes

*all codes
* ...

**Comment by GriffinG1** [comment]
Please actually include the title ID and product code. You should be able to find both through FBI>Titles

**Comment by JourneyOver** [comment]
As Griffin mentioned, all codes for Yokai-Watch 1 are for 1.0 only, so either downgrade your game version by deleting the update and try the codes again, or you can look around or make your own for the latest version and send us a PR and we will gladly accept it. On top of all this, next time please fill out all information pertaining to the game otherwise it's automatic dismissal and closure of the issue.

As it stands right now though I am closing this issue, due to the fact that you are on version 1.2 of the game, while the codes are all 1.0, if you by chance get around to downgrading your game to 1.0 and testing the codes again and they do not work then feel free to either open this issue again or create a new one. If you re-open this issue, please update the OP with all the information needed.

Thanks!
Journey
