### ISSUE TITLE
Codes not working

### ISSUE THREAD

**Issue by MercuryGamer** [FlagBrew/Sharkive#171]
## Issue template

* [] Issue with one or more codes in the database

### In some games the codes doesn't work or 2 codes are activated but one deactivates the other ones

* **3DS**:
* **Medarot Dual, Medarot 7, Medarot 8, Pokemon Crystal, Pokemon Yellow, The Legend of Zelda: Hyrule Warriors, Sonic Generations, Kirby Planet Robobot, Dragon Ball Fusions, Pokemon Omega Ruby, Pokemon Ultra Sun, Shantae & The Pirate's Curse, Mario & Luigi Bowser's Inside Story and Dragon Ball Z Extreme Butoden**:
* **Product code**:
* **Most recent (not Medarot Dual, still looking for update)**:
* **Most recent**:
* **Atmosphere-NX version**:

### Not working codes
Medarot Dual
* All Codes

Medarot 7
* All Codes

Medarot 8
* All Codes

The Legend of Zelda Hyrule Warriors
* All codes

Sonic Generations
* All codes

Shantae & The Pirate's Curse
*All Codes

Pokemon Crystal
* Only Shiny works

Pokemon Yellow
*All Codes

Pokemon Omega Ruby
* All Codes

Dragon Ball Fusions
*All Codes

Dragon Ball Z Extreme Butoden
* All Codes

Sonic Generations
*All Codes

Kirby Planet Robobot
*All Codes

Note: Some of them work but is very hard because is pressing buttons but not always work (Like Pokemon Crystal Catch Trainer's Pokemon Code)

**Comment by JourneyOver** [comment]
Okay this issue is a complete mess, please follow the below rules..

1. Fill out separate issues or make one issue.
1.5 make new comments for each game if you go the one issue route.
2. While filling out the issue('s) make sure you fill out the entire information for the `Fill this for problems with codes in the database` Correctly.. not doing so will cause issue closer (without removal of any actual broken codes) within 7 days if I require you to fix it and you don't.
3. For some games the codes only work on a specific version, so instead of saying `All Codes` you need to write down what codes actually don't work.

Please fix this issue following the above, you have 7 days to do so or this issue will be closed.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
