### ISSUE TITLE
Pokemon Moon Code Issues

### ISSUE THREAD

**Issue by DakrFH** [FlagBrew/Sharkive#192]
* **Platform**:3DS
* **Title ID**:00175E00
* **Product code**:CTR-P-BNEA
* **Game version**:1.2
* **Luma version**:10.0.1

### Not working codes

* code 1: (SELECT + UP)All Clothes(male) v1.2
* code 2:  (SELECT + UP)All MEDICINE(male) v1.2
* code 3: No Outlines v1.2

**Comment by JourneyOver** [comment]
Tested these codes and they work fine, for the (select + up) codes you can only have 1 active at a time otherwise they don't work. (so you'd need to do one (select + up) code and then save and exit and reload the game and do the next (select + up) code and so on and so forth for all (select + up) codes or really any codes that use a duplicate button combo)

Closing this as these codes are working just fine.
