### ISSUE TITLE
(Request) V1.2 Ultra Moon to Sun

### ISSUE THREAD

**Issue by Elemental65** [FlagBrew/Sharkive#195]
Sorry to waste time or something, but I was wondering if you can add the ultra moon v1.2 cheats to the ultra sun version?

Don't kill me please

**Comment by JourneyOver** [comment]
Sadly it's not as easy as a copy/paste from one to the other like some of the older pokemon games, due to byte changes between both games.

Also nobody currently on the FlagBrew team makes cheats. Everything in Sharkive's database comes from user submissions. If you have some working cheats for your game and want them included in Sharkive, submit a pull request and someone will get around to adding them.

You are free to try adding some of the codes from UM to US yourself though and if you find out they work then you are free to submit a Pull Request with said working codes added.
