### ISSUE TITLE
animal crossing new leaf welcome amiibo europe EUR / PAL

### ISSUE THREAD

**Issue by bluesky37** [FlagBrew/Sharkive#222]
## Issue template

* [] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 6fe9314   i don't know ... Animal crossing new leaf Welcome amiboo
* **Product code**: ?
* **Game version**: Welcome amiibo ver. 1.5 (2012+2016 nintendo)
* **Luma version**:  10.1.3.-3143e7e
* **Atmosphere-NX version**: ?

### Not working codes

All code - not working

[L+A for 99k Bells in slot 1]
DD000000 00000201
D3000000 10000000
25FBEDD0 00000012
25FBEDD1 00000021

[L+A all item slots are 99k Bells]
DD000000 00000201
D3000000 10000000
C0000000 00000010
25FBEDD0 00000012
25FBEDD1 00000021
DC000000 00000004
D1000000 00000000

[L+A to clear inv slot 1]
DD000000 00000201
D3000000 10000000
25FBEDD0 000000FE
25FBEDD1 0000007F

[Item Duplication (L copy, R paste)]
DD000000 00000200
D9000000 15FBEDD0
D6000000 15FBED60
D0000000 00000000
DD000000 00000100
D9000000 15FBED60
D6000000 15FBEDD0

**Comment by JourneyOver** [comment]
Couple things:

1. `Title ID: 6fe9314 i don't know ... Animal crossing new leaf Welcome amiboo`

We need to know the title ID (which what you put is not the Title ID) to be able to remove the codes from the correct Title. You can find the end of the Title ID in checkpoint whenever you scroll over a game.

2. ACNL has issues with codes, because there are different types of this game, those being - Game + DLC (DLC installed separately) / AIO (DLC included with the game instead of having to install it separately), and the cheat codes are different between each one of those (from what I remember) on top of updates possibly changing the code. It's advised to use Plugins instead of cheats for any ACNL games at this time.

so in theory you are probably running into 2, but at this point in time I think I am just going to remove all the codes for ACNL completely due to the fact that we have had to many issues and I had already removed the USA version a while back due to this exact same thing.
