### ISSUE TITLE
Pokemon Ultra Sun cheats issue

### ISSUE THREAD

**Issue by Mr-ZombieSteam** [FlagBrew/Sharkive#237]
Platform (3DS/Switch): 3DSXL
Title ID: 00040000001B5000
Product code: CTR-P-BPXP
Game version: v1.2
Luma version: 10.2-bb07a73
Checkpoint Version: 3.7.4

CHEATS:
100% Catch Rate (work around is using the all items cheat for all PokeBalls/Master Balls)

Catch Trainer Pokemon - tried only for Version 1.2 - crashes the game after a few steps. 

Also, for the other item codes and money code for v1.2 I've noticed after you enable the cheat if you try to move around or save the game it will crash. 

However if you enable, activate, then disable the cheat you can save and carry on playing.

Thanks!

**Comment by JourneyOver** [comment]
since you are making an issue with mention of crashing you are more than likely running into a kernel bug that SUMO and USUM (and tbh probably the older pokemon games as well) have with cheats. Luma's cheat engine would need to be redesigned to fix this, which would cause another bug elsewhere. As such, there is no solution to this problem at this time besides using another console.

Since this is an issue we can not fix I am closing this.
