### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by wrenchy-matt** [FlagBrew/Sharkive#291]
Hi, when I want to use a cheat in any of my Pokemon games (Alpha Sapphire, Y, Moon and Ultra Moon), it crashes and give me an error screen

**To Reproduce**
1. Launch 'Pokemon Alpha Sapphire (EUR)' or any of the games mentioned above
2 Press the 'L+Down+select' buttons
3. selct the choosen cheats
4. Pres the B button twice
5. Launch the game
6. 'Error screen'

**Expected behavior**
I expected my game to run normally and cheats to work

**Screenshots**
(This screen is from the Alpha Sapphire scenario)
![image](https://user-images.githubusercontent.com/104130537/167908019-8f076468-dc14-47fa-b60e-931be7a41330.png)

**3DS:**
- Entrypoint: .cia
- System version: 11.15.0-47E
- Checkpoint version: 3.7.4
- Result code (if available):

**Additional context**
My console is a 3DS XL EUR model

**Comment by wrenchy-matt** [comment]
ok, thanks
also, I tried to turn on cheats when I'm in game, but it still crash with the same error message

**Comment by wrenchy-matt** [comment]
The cheats I used are 'Hold R at route 116 - Catch Mew with PokeNav' and 'Shiny Pokemon with radar (Hold R)'

**Comment by GriffinG1** [comment]
This may be the cause, someone will have to test the codes on another console to be sure. If they are indeed broken codes, they'll be removed. It's possible they're meant for a specific game version, too, though since they aren't marked as such it's a pain to confirm that.

![image](https://user-images.githubusercontent.com/28538707/167915630-7205884a-65c3-419b-b933-43757f810377.png)

**Comment by wrenchy-matt** [comment]
oh, ok, thank you
