### ISSUE TITLE
FE shadows of Valentia crash

### ISSUE THREAD

**Issue by GonXdramon** [FlagBrew/Sharkive#89]
## Issue template

* [] Sharkive itself doesn't cause any problems
* [] Every single code crashes the game and it forces it to restart the 3ds

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
* **Encountered behavior**:

### Fill this for problems with codes in the database

* **Title ID**:
* **Product code**:
* **Game version**:

### Not working codes

* code 1
* code 2
* ...

**Comment by JourneyOver** [comment]
As you have provided no information on the titleid/product code/game version/region/nor any codes that cause said crash this issue is going to be closed.

You are free to edit your issue and input the information and then reopen the issue but failure to complete information will result in another closure.
