### ISSUE TITLE
Super Mystery Dungeon No Working Codes 

### ISSUE THREAD

**Issue by callmechknnugz** [FlagBrew/Sharkive#95]
* **Title ID**: 0004000000174400
* **Product code**: CTR-P-BPXP
* **Game version**: 0 (0.0.0)

### Not working codes
So far all of the codes I’ve tested have not worked. 

Also: if you could please somehow add the code “item x999 after deposit” it would be very much appreciated.

**Comment by JourneyOver** [comment]
I have a feeling that the issue with this one is the same as issue #47 in that the codes are for an older version of the game, if possible could you delete any update data for the game and please retest the codes? Preferably with Luma Nightly so things will be accurate.

If there was never an update for the European version then please retest the codes again with Luma Nightly anyways as it's a requirement for any code issue (at least until the next official release of Luma)

As for code requests, if the code for "item x999 after deposit"" already exists somewhere then please add a link to said code and it will be added when I get my computer situation taken care of and I'm able to do updates again.

**Comment by JourneyOver** [comment]
Just a note but if you fail to reply within the next 7 days stating that you have tested the codes on both Luma Nightly and on a lower version of the game (lower version usually isn't required but this is a specific case due to an almost duplicate issue) and that they work or not, this issue will be closed without anything done.

**Comment by JourneyOver** [comment]
Closed due to inactivity.
