### ISSUE TITLE
Pokemon Y Report

### ISSUE THREAD

**Issue by CptDinosaur** [FlagBrew/Sharkive#96]
## Issue template

* [ ] Issue with Sharkive
* [x] Issue with one or more codes in the database

### Fill this for problems with codes in the database

* **Title ID**: 0004000000055E00
* **Product code**: CTR-P-EK2A
* **Game version**: 1.5
* **Luma version**: 9.1-bd15f51 (Nightly)

### Not working codes
First things first: The whole thing doesn't work
I think Luma's Rosalina menu has a hard limit on the number of codes, around 3 pages, and there are more than that here. I removed all the pokemon slot related codes (like 1000 lines) and I can now see the rest. If the pkmn modifier codes are removed, there'll be enough lines for the other codes.

Other than that, codes that don't work:
* Egg Instant Hatch v1.5
* 100%Catch v1.5 [The main reason I even use cheats :( ]
* Catch Trainer's Pokemon v1.5

I assume the same is true for Pokemon X

**Comment by CptDinosaur** [comment]
Actually ocarina of time has like 5 pages. Maybe it's a line limit not a code limit? Idk

**Comment by JourneyOver** [comment]
Hello,

Please test the codes again with the latest [Luma nightly](https://github.com/hax0kartik/luma-hourlies/releases) as it has several fixes for cheat compatibility, if the codes continue to not work then please let me know. Failing to do so within 7 days will result in the issue being closed without removal of broken codes. 

Thank you!

**Comment by JourneyOver** [comment]
> I think Luma's Rosalina menu has a hard limit on the number of codes, around 3 pages, and there are more than that here. I removed all the pokemon slot related codes (like 1000 lines) and I can now see the rest. If the pkmn modifier codes are removed, there'll be enough lines for the other codes.

Yes there is a limit on how many codes Luma cheat menu can show, and idk if it'll ever be risen or not. There are a couple of games (most being Pokemon games but there are a couple of non Pokemon) that have pretty big lists of codes that will require the person that is wanting to use the codes to go in and pick and choose what codes they want manually.

As for the broken codes thanks for the report now that you are testing with the Luma nightly, they will be removed eventually but due to me being the only one who takes care of the DB it will be some time as I currently don't have a computer (broken and in repair shop).
