### ISSUE TITLE
Recommendation to find broken codes

### ISSUE THREAD

**Issue by CptDinosaur** [FlagBrew/Sharkive#98]
We could do with a site that has a list of all the games, and people can mark the games as "Working" or "Broken Codes" and then say which codes are broken. Right now people might be reporting on games or checking games people already know are broken

**Comment by JourneyOver** [comment]
Before my computer broke I was working on a wiki page that listed every game in the database, but due to well my computer breaking that wiki page has kinda been put on hold until my computer situation has been resolved (sadly I can't give a date on when that will be) as for the "broken" "working" bit of your suggestion honestly I prefer issues even if we do end up with a duplicate at some point, as 99% of the time before my computer situation happened broken codes was usually removed within the hour of an issue being posted.
